### ISSUE TITLE
enqueue_at() does not respect result_ttl argument

### ISSUE THREAD

**Issue by Kilte** [rq/rq-scheduler#135] opened 2016-09-08 07:46 UTC
Steps to reproduce:

`q.py`:

``` python
from datetime import datetime, timedelta
from redis import Redis
from rq_scheduler import Scheduler
from jobs import my_job

redis = Redis()
my_scheduler = Scheduler(connection=redis, queue_name='my_queue')
start_time = datetime.utcnow() + timedelta(seconds=5)
my_scheduler.enqueue_at(start_time, my_job, 'test', result_ttl=0)

```

`jobs.py`:

``` python
def my_job(arg):
    print('Call: my_job(%s)' % arg)

```

run:

``` sh
rqscheduler &
python q.py
rqworker my_queue
```

result:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.4/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
TypeError: my_job() got an unexpected keyword argument 'result_ttl'
```

**Comment by emin63** [comment] 2017-02-02 17:02
Also, enqueue_at does not support queue_name. The problem is that it is just passing all *args and **kwargs to the job.

I could try to fix and create a pull request if that would help. Are pull requests desired? It seems like they sometimes languish for a long time. Is there a better way to help fix bugs?

Thanks,
-Emin

**Comment by selwin** [comment] 2017-02-03 08:28
@emin63 yes, please open a PR if you can.

**Comment by emin63** [comment] 2017-02-07 03:22
OK, pull request submitted. Thanks.

**Comment by selwin** [comment] 2018-01-30 00:34
This is fixed in master

**Closed by selwin** 2018-01-30 00:34 UTC
